== Java - PyTorch Demo (Deep Java Learning)

The Deep Java Library (DJL) is a high-level, engine-agnostic framework for deep learning in Java. It provides APIs to train and deploy models without requiring deep knowledge of specific deep learning engines. PyTorch is a popular open-source machine learning framework, known for its flexibility and ease of use, particularly in research and prototyping. DJL supports PyTorch as one of its backend engines, allowing Java developers to leverage PyTorch models within their applications.

DJL's PyTorch engine enables the execution of PyTorch models in a Java environment. This integration simplifies the deployment of PyTorch models in production systems, especially those built on Java. It handles the complexities of native library management and provides a consistent API for inference, regardless of the underlying framework. To use PyTorch with DJL, one must include the appropriate PyTorch engine dependency in their project. DJL can load PyTorch models, including those from the PyTorch model zoo, and run inference using them. It's important to manage dependencies correctly, as DJL supports multiple engines, and including unnecessary ones can increase memory consumption.

In this demo we show an introductory example of using a custom model (cruise-drink-package) to inference (predict) based upon a given input.

== Custom Model

Our custom was trained upon a dataset representing cruise passenger drink package purchase data.

[,text,linenum]
----
Age: Number > 0
Gender: 0 (female), 1 (male)
Itinerary: SKU code for ship route. 0 -> 2 (three different routes).
Loyalty Level: No Level (0), Bronze (1), Silver(2), Gold(3).
Drink Package: No Package, Soda & Juices, Coffee/Tea/Hot Chocolate, Alcohol, Premium
----

To help illustrate trends we're going to assume route 0 is a northern itinerary (preference for hot drinks), and route 2 is tropical (refreshment).

=== Prediction Purpose

The model seeks to aid marketers in targeting sales to a specific passenger based upon cruiser trends. Given known passenger information (Age, Gender, Itinerary, Loyalty Level) which Drink Package upsell is most likely to be sold if offered.

ex:
 What drink package would a 35-year-old Male with Silver loyalty on Itinerary 1 likely purchase?


== Build

[,text,linenum]
----
mvn clean install
----

== Run

[,text,linenum]
----
mvn exec:java -Dexec.mainClass="com.savoir.java.pytorch.demo.PyTorchDemo"
----
